### PR TITLE
fix: Fix convert from jsonb to dozer type

### LINKED ISSUE #1077: Postgres jsonb type fails in type conversion
https://github.com/getdozer/dozer/blob/main/dozer-ingestion/src/connectors/postgres/helper.rs
```
Type::JSONB | Type::JSON => Ok(Field::Bson(v.to_vec())),
```

### PR DESCRIPTION
**Pull request by karolisg**
Fixes #1077

### CODE REVIEW

File: dozer-ingestion/src/connectors/postgres/helper.rs [hunk 1]
```diff
@@ -144,8 +144,13 @@ pub fn value_to_field(
             value.map_or_else(handle_error, |v| Ok(Field::Binary(v)))
         }
         &Type::JSONB => {
-            let value: Result<Vec<u8>, _> = row.try_get(idx);
-            value.map_or_else(handle_error, |v| Ok(Field::Bson(v)))
+            let value: Result<serde_json::Value, _> = row.try_get(idx);
+
+            value.map_or_else(handle_error, |v| {
+                Ok(Field::Bson(
+                    serde_json::to_vec(&v).map_err(|e| JSONBParseError(e.to_string()))?,
```
Comment (chubei) [inline dozer-ingestion/src/connectors/postgres/helper.rs:151]: Should it be `bson::to_vec`?

Comment (karolisg) [reply dozer-ingestion/src/connectors/postgres/helper.rs]: Changed to bson

**Review by chubei — APPROVED** [review]
